PUT http://localhost:3000/api/actualizar/67943266ca88560a5ce7afd1
Content-Type: application/json

{
  "titulo": "tarea actualizada",
  "descripcion": "Leer y actualizar la documentación del proyecto.",
  "prioridad": "HIGH",
  "estado": "pending",
  "personaEncargada": "Juan Pérez"
}
